function noaa_co2 = importfile_surf_CO2_2019_02_22(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   CO2GHGREFERENCE = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   CO2GHGREFERENCE = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   co2GHGreference = importfile('co2_GHGreference.1414526941_surface.txt', 79, 1951);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/02/22 10:29:49

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 79;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column72: double (%f)
%   column73: double (%f)
%	column74: double (%f)
%   column75: double (%f)
%	column76: double (%f)
%   column77: double (%f)
%	column78: double (%f)
%   column79: double (%f)
%	column80: double (%f)
%   column81: double (%f)
%	column82: double (%f)
%   column83: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
co2GHGreference = table;
co2GHGreference.VarName1 = dataArray{:, 1};
co2GHGreference.VarName2 = dataArray{:, 2};
co2GHGreference.VarName3 = dataArray{:, 3};
co2GHGreference.VarName4 = dataArray{:, 4};
co2GHGreference.VarName5 = dataArray{:, 5};
co2GHGreference.VarName6 = dataArray{:, 6};
co2GHGreference.VarName7 = dataArray{:, 7};
co2GHGreference.VarName8 = dataArray{:, 8};
co2GHGreference.VarName9 = dataArray{:, 9};
co2GHGreference.VarName10 = dataArray{:, 10};
co2GHGreference.VarName11 = dataArray{:, 11};
co2GHGreference.VarName12 = dataArray{:, 12};
co2GHGreference.VarName13 = dataArray{:, 13};
co2GHGreference.VarName14 = dataArray{:, 14};
co2GHGreference.VarName15 = dataArray{:, 15};
co2GHGreference.VarName16 = dataArray{:, 16};
co2GHGreference.VarName17 = dataArray{:, 17};
co2GHGreference.VarName18 = dataArray{:, 18};
co2GHGreference.VarName19 = dataArray{:, 19};
co2GHGreference.VarName20 = dataArray{:, 20};
co2GHGreference.VarName21 = dataArray{:, 21};
co2GHGreference.VarName22 = dataArray{:, 22};
co2GHGreference.VarName23 = dataArray{:, 23};
co2GHGreference.VarName24 = dataArray{:, 24};
co2GHGreference.VarName25 = dataArray{:, 25};
co2GHGreference.VarName26 = dataArray{:, 26};
co2GHGreference.VarName27 = dataArray{:, 27};
co2GHGreference.VarName28 = dataArray{:, 28};
co2GHGreference.VarName29 = dataArray{:, 29};
co2GHGreference.VarName30 = dataArray{:, 30};
co2GHGreference.VarName31 = dataArray{:, 31};
co2GHGreference.VarName32 = dataArray{:, 32};
co2GHGreference.VarName33 = dataArray{:, 33};
co2GHGreference.VarName34 = dataArray{:, 34};
co2GHGreference.VarName35 = dataArray{:, 35};
co2GHGreference.VarName36 = dataArray{:, 36};
co2GHGreference.VarName37 = dataArray{:, 37};
co2GHGreference.VarName38 = dataArray{:, 38};
co2GHGreference.VarName39 = dataArray{:, 39};
co2GHGreference.VarName40 = dataArray{:, 40};
co2GHGreference.VarName41 = dataArray{:, 41};
co2GHGreference.VarName42 = dataArray{:, 42};
co2GHGreference.VarName43 = dataArray{:, 43};
co2GHGreference.VarName44 = dataArray{:, 44};
co2GHGreference.VarName45 = dataArray{:, 45};
co2GHGreference.VarName46 = dataArray{:, 46};
co2GHGreference.VarName47 = dataArray{:, 47};
co2GHGreference.VarName48 = dataArray{:, 48};
co2GHGreference.VarName49 = dataArray{:, 49};
co2GHGreference.VarName50 = dataArray{:, 50};
co2GHGreference.VarName51 = dataArray{:, 51};
co2GHGreference.VarName52 = dataArray{:, 52};
co2GHGreference.VarName53 = dataArray{:, 53};
co2GHGreference.VarName54 = dataArray{:, 54};
co2GHGreference.VarName55 = dataArray{:, 55};
co2GHGreference.VarName56 = dataArray{:, 56};
co2GHGreference.VarName57 = dataArray{:, 57};
co2GHGreference.VarName58 = dataArray{:, 58};
co2GHGreference.VarName59 = dataArray{:, 59};
co2GHGreference.VarName60 = dataArray{:, 60};
co2GHGreference.VarName61 = dataArray{:, 61};
co2GHGreference.VarName62 = dataArray{:, 62};
co2GHGreference.VarName63 = dataArray{:, 63};
co2GHGreference.VarName64 = dataArray{:, 64};
co2GHGreference.VarName65 = dataArray{:, 65};
co2GHGreference.VarName66 = dataArray{:, 66};
co2GHGreference.VarName67 = dataArray{:, 67};
co2GHGreference.VarName68 = dataArray{:, 68};
co2GHGreference.VarName69 = dataArray{:, 69};
co2GHGreference.VarName70 = dataArray{:, 70};
co2GHGreference.VarName71 = dataArray{:, 71};
co2GHGreference.VarName72 = dataArray{:, 72};
co2GHGreference.VarName73 = dataArray{:, 73};
co2GHGreference.VarName74 = dataArray{:, 74};
co2GHGreference.VarName75 = dataArray{:, 75};
co2GHGreference.VarName76 = dataArray{:, 76};
co2GHGreference.VarName77 = dataArray{:, 77};
co2GHGreference.VarName78 = dataArray{:, 78};
co2GHGreference.VarName79 = dataArray{:, 79};
co2GHGreference.VarName80 = dataArray{:, 80};
co2GHGreference.VarName81 = dataArray{:, 81};
co2GHGreference.VarName82 = dataArray{:, 82};
co2GHGreference.VarName83 = dataArray{:, 83};

lat_sine = [-1	-0.95	-0.9	-0.85	-0.8	-0.75	-0.7	-0.65	-0.6	-0.55	-0.5	-0.45	-0.4	-0.35	-0.3	-0.25	-0.2	-0.15	-0.1	-0.05	0	0.05	0.1	0.15	0.2	0.25	0.3	0.35	0.4	0.45	0.5	0.55	0.6	0.65	0.7	0.75	0.8	0.85	0.9	0.95	1];
noaa_co2.Matlab_time = datenum(co2GHGreference{:,1},0,1);
noaa_co2.lat_co2 = asind(lat_sine)';

noaa_co2.co2_atmos = NaN(length(noaa_co2.Matlab_time), length(noaa_co2.lat_co2));
noaa_co2.co2_atmos = co2GHGreference{:,2:2:end}';
noaa_co2.co2_atmos_std = co2GHGreference{:,3:2:end}';

